name: Create torrent
on:
  push:
    branches:
      - master
      
env:
  name: "Assassin's Creed: Brotherhood"
  comment: "Assassin's Creed: Brotherhood"
  url: "https://download131.uploadhaven.com/1/application/zip/rFer4DUYYE1X5izl1lI7dFS4svCR2h3VJQDkYOik.zip?key=Ha9LPyKMpb1drVbEU_EVlw&expire=1749249974&filename=Assassins.Creed.Brotherhood.v1.03.zip"
  file_name: "Assassin's Creed: Brotherhood"
  piece_size: 4 194 304 # Check the README.md for recommended piece size
      
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Install mktorrent
        run: sudo apt-get install mktorrent
        
      - name: Download file
        run: wget -nv -O "$file_name" "$url"
        
      - name: Create torrent using mktorrent
        run: mktorrent -c "$comment" -l $piece_size -o "${name}.torrent" -w "$url" "$file_name"
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.torrent
